parameters:
  # Agent
  - name: poolName
    type: string

  - name: agentName
    type: string

  # Registry
  - name: imageName
    type: string

stages:
  # CI Stage
  - stage: Build
    displayName: "Build Docker Image"
    variables:
      imageTag: "$(Build.BuildId)"
      rootPath: "$(Build.SourcesDirectory)"
      dockerfilePath: "$(Build.SourcesDirectory)/Performance/Dockerfile"
    jobs:
      - job: BuildImage
        displayName: "Build Docker Image"
        pool:
          name: ${{ parameters.poolName }}
          demands:
            - Agent.Name -equals ${{ parameters.agentName }}
        steps:
          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              command: build
              repository: ${{ parameters.imageName }}
              dockerfile: "$(dockerfilePath)"
              buildContext: "$(rootPath)"
              tags: |
                $(imageTag)
                latest
