FROM mcr.microsoft.com/azure-sql-edge:latest

USER root

# Install curl and tar to download go-sqlcmd
RUN apt-get update -y && apt-get install -y curl tar && \
    curl -L -o /tmp/sqlcmd.tar.gz \
      https://github.com/microsoft/go-sqlcmd/releases/download/v1.8.2/sqlcmd-linux-arm64.tar.gz && \
    tar xzf /tmp/sqlcmd.tar.gz -C /usr/local/bin && \
    rm /tmp/sqlcmd.tar.gz && \
    chmod +x /usr/local/bin/sqlcmd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/usr/local/bin"

USER mssql